training:
  lr: 0.001
  weight-decay: 0.0000001
  bs: 12 # batch-size
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 30 # Equidistant frames
  mask-method: 'black' # 'black', 'noise' or 'none'
  mask-number: 8 # range(0, 9)
  picture-color: 'rgb' # 'rgb' or 'gray'
  aug: 'no' # if use aug

model:
  image-size: 224
  SRM-net: 'no' # use SRM net or not.'yes' or 'no'